import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'demo_label'), ['label.c'])
env.Program(os.path.join(BIN_DIR, 'demo_button'), ['button.c'])
env.Program(os.path.join(BIN_DIR, 'demo_check_button'), ['check_button.c'])
env.Program(os.path.join(BIN_DIR, 'demo_dialog'), ['dialog.c'])
env.Program(os.path.join(BIN_DIR, 'demo_edit'), ['edit.c'])


