import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'demo_label'), ['label.c'])
env.Program(os.path.join(BIN_DIR, 'demo_button'), ['button.c'])
env.Program(os.path.join(BIN_DIR, 'demo_check_button'), ['check_button.c'])
env.Program(os.path.join(BIN_DIR, 'demo_dialog'), ['dialog.c'])
env.Program(os.path.join(BIN_DIR, 'demo_edit'), ['edit.c'])
env.Program(os.path.join(BIN_DIR, 'demo_image'), ['image.c'])
env.Program(os.path.join(BIN_DIR, 'demo_rich_text'), ['rich_text.c'])
env.Program(os.path.join(BIN_DIR, 'demo_slider'), ['slider.c'])
env.Program(os.path.join(BIN_DIR, 'demo_progress_bar'), ['progress_bar.c'])
env.Program(os.path.join(BIN_DIR, 'demo_spin_box'), ['spin_box.c'])
env.Program(os.path.join(BIN_DIR, 'demo_basic'), ['basic.c'])
env.Program(os.path.join(BIN_DIR, 'demo_combo_box'), ['combo_box.c'])


